server {
    listen 80;
    
    # Chỉ định thư mục chứa file tĩnh do React sinh ra
    root /usr/share/nginx/html;
    index index.html index.htm;
    
    # Quy tắc quan trọng nhất cho Single Page Application (React Router)
    # Bất kể người dùng gõ URL gì, nếu file không tồn tại thì tự động trả về index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
