version: '3.8'

services:
  # 1. Database PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: task_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: manage_task
    ports:
      - "5432:5432" # Phơi bày port 5432 ra ngoài để ta có thể dùng DBeaver xem Data
    volumes:
      # Ánh xạ file init.sql vào thư mục khởi tạo để tự động tạo bảng lúc đầu
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # Lưu trữ dữ liệu vật lý ra ngoài để nếu tắt container không bị mất dữ liệu
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Ứng dụng Backend (Auth Service)
  backend-auth:
    build:
      context: ./backend-auth
      dockerfile: Dockerfile
    container_name: task_backend_auth
    environment:
      - DB_HOST=db       # Trỏ tên host vào thẳng cái thùng "db" ở trên
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=auth_db
      - DB_PORT=5432
      - JWT_SECRET=secret_key_123
      - PORT=5001
    ports:
      - "5001:5001"
    depends_on:
      db:
        # Bắt buộc phải đợi thùng db khởi động xong hoàn toàn (xanh healthcheck) mới được chạy
        condition: service_healthy

  # 3. Ứng dụng Backend (Task Service)
  backend-tasks:
    build:
      context: ./backend-tasks
      dockerfile: Dockerfile
    container_name: task_backend_tasks
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=task_db
      - DB_PORT=5432
      - JWT_SECRET=secret_key_123
      - PORT=5002
    ports:
      - "5002:5002"
    depends_on:
      db:
        condition: service_healthy

  # 3. Ứng dụng Frontend (React + Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task_frontend
    ports:
      - "3000:80"  # Nginx bên trong chạy cổng 80, nhưng ta truy cập ở ngoài bằng http://localhost:3000
    depends_on:
      - backend-auth
      - backend-tasks

# Khai báo ổ cứng ảo để lưu dữ liệu DB vĩnh viễn
volumes:
  pgdata:
