apiVersion: v1
kind: ConfigMap
metadata:
  name: task-config
  namespace: manage-task
data:
  DB_HOST: "postgres-service"
  DB_USER: "postgres"
  DB_NAME: "task_db"
  DB_PORT: "5432"
  JWT_SECRET: "secret_key_123"
  PORT: "5002"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
  namespace: manage-task
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task-service
          # Thay 'your-dockerhub-username' bằng username thật trên Docker Hub của bạn
          image: your-dockerhub-username/manage-task-tasks:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5002
          envFrom:
            - configMapRef:
                name: task-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
  namespace: manage-task
spec:
  selector:
    app: task-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP
